/**
 * MSW browser worker — used in dev-preview pages for Playwright screenshots.
 * Intercepts fetch() calls in the browser via a service worker.
 *
 * The service worker file (public/mockServiceWorker.js) is generated by:
 *   npx msw init public/ --save
 */
import { setupWorker } from "msw/browser";
import { handlers } from "./handlers";

export const worker = setupWorker(...handlers);
